### In this exam you should use only the numpy library functions for any operations. All the way from creating arrays to any operations on the arrays.
You can refer to the scipy docs for arriving at your answer. https://docs.scipy.org/doc/numpy/reference/

In [2]:
import numpy as np

#### 1. Create a null vector of size 10 but the fifth value is 1

In [15]:
a = np.zeros((1,10)) # Create an null vector of size 10
a[0,4]=1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


### <font color = blue>Correct answer </font>

In [20]:
# NOTE: (1,10) is not a vector. It is a matrix
a = np.zeros((10))
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 and print its mean value

In [37]:
x =  np.arange(0, 9).reshape(3,3)
print(x.mean())

4.0


## <font color = red>Good</font>

In [22]:
randomMatrix = np.random.random((1,3,3))  # Create an array filled with random values
print(randomMatrix)   

[[[0.58400689 0.18973043 0.58937289]
  [0.83517546 0.95673067 0.50790444]
  [0.86493797 0.93681792 0.8368127 ]]]


### <font color = blue>Correct answer </font>

In [9]:
np.random.random((3,3,3))

array([[[0.66504628, 0.41459092, 0.59009874],
        [0.41221242, 0.85910296, 0.00406377],
        [0.23990219, 0.16275058, 0.36757355]],

       [[0.42886793, 0.6202743 , 0.33168693],
        [0.33971737, 0.06457611, 0.50375297],
        [0.84293454, 0.22348822, 0.8371757 ]],

       [[0.68527215, 0.0981342 , 0.17008871],
        [0.19648177, 0.98968956, 0.01285111],
        [0.62865288, 0.77305531, 0.84343979]]])

#### 4. Create a 4x4 matrix with all 1s in the border and 0 inside

In [24]:
onesBordersMatrix = np.ones((4,4))
print("Original array")
print(onesBordersMatrix)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(onesBordersMatrix)

Original array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### <font color = blue>Correct answer </font>

In [19]:
zeroM = np.zeros((4,4))
zeroM[0,:] = 1
zeroM[:,0] = 1
zeroM[-1,:] = 1
zeroM[:,-1] = 1
print(zeroM)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### <font color = blue>Better solution</font>

In [18]:
zeroB = np.zeros((2,2))
np.pad(zeroB,(1,1), 'constant', constant_values =1)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 5. Pad an existing array from question 2 with zeros and make it a 4x4 array

In [38]:
x = np.pad(x,[(0,0),(0, 1)], mode='constant')
print(x)

[[0 1 2 0]
 [3 4 5 0]
 [6 7 8 0]]


#### 6. Create a 5x5 matrix with 1,2,3,4,5 in the diagonal and zeros for all other elements

In [48]:
a6 = np.zeros((5,5), int)
print(a6)
np.fill_diagonal(a6, range(1,6))
print(a6)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## <font color = red> Very good </font>

#### 7. Create an 8x8 matrix and fill it with checkerboard pattern (0s and 1s)

In [52]:
a7 = np.zeros((8,8), int)
a7[1::2, ::2] = 1
a7[::2, 1::2] = 1
print(a7)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## <font color = red>Very good</font>

In [11]:
# Alternate solution .. Simple
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
